services:

  traefik:
    image: traefik:v3.6.5
    container_name: traefik
    command:
    - "--log.level=ERROR"
    - "--api.insecure=true"
    - "--providers.docker=true"
    - "--providers.docker.exposedbydefault=false"
    - --providers.file.directory=/etc/traefik/dynamic
    - --providers.file.watch=true
    - "--entryPoints.web.address=:80"
    - "--entryPoints.websecure.address=:443"
    - "--entrypoints.websecure.http.tls=true"
    - "--entrypoints.websecure.forwardedHeaders.trustedIPs=127.0.0.1/32,10.0.0.0/8,172.16.0.0/12,192.168.0.0/24"
    - "--certificatesresolvers.based.acme.email=bulynin.misha@gmail.com"
    - "--certificatesresolvers.based.acme.storage=/letsencrypt/acme.json"
    - "--certificatesresolvers.based.acme.dnsChallenge.provider=cloudflare"
    - "--metrics.prometheus=true"
    - "--accesslog=true"
    env_file:
    - stack.env
    ports:
    - "80:80"
    - "443:443"
    - "8088:8080"
    volumes:
    - "/var/run/docker.sock:/var/run/docker.sock:ro"
    - "letsencrypt:/letsencrypt"
    - ./dynamic:/etc/traefik/dynamic/:ro
    restart: unless-stopped
    networks:
      - traefik_proxy
    labels:
    - "traefik.enable=true"
    - "traefik.http.routers.traefik.entrypoints=websecure"
    - "traefik.http.services.traefik.loadbalancer.server.port=8080"
    - "traefik.http.routers.traefik-secure.entrypoints=websecure"
    - "traefik.http.routers.traefik-secure.rule=Host(`traefik.home.m1xxos.tech`)"
    - "traefik.http.routers.traefik-secure.tls=true"
    - "traefik.http.routers.traefik-secure.tls.certresolver=based"
    - "traefik.http.routers.traefik-secure.tls.domains[0].main=home.m1xxos.tech"
    - "traefik.http.routers.traefik-secure.tls.domains[0].sans=*.home.m1xxos.tech"
    - "traefik.http.routers.traefik-secure.service=api@internal"

networks:
  traefik_proxy:
    external:
      name: traefik_proxy

volumes:
  letsencrypt: